config/routes.rb
Rails.application.routes.draw do
  
  
  resources :questions do
  	resources :codes
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/code.rb
class Code < ApplicationRecord
	belongs_to :question
	belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
	has_many :codes
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :codes
         has_many :questions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
  before_action :set_code, only:[:edit,:show,:update,:destroy]
   before_action :authenticate_user!


  def index
  	@codes = Code.all
  end

  def edit

  end

  def new
    @p = Question.find(params[:question_id])
    @code = @p.codes.build
    cookies[:p_id] = @p.id

    

  end

  def create
  	@code = Code.create(set_params)
    @code.user_id = current_user.id
    @code.question_id = cookies[:p_id]
    @code.save
    redirect_to controller: 'questions' , action: 'show' , id: cookies[:p_id]
    

  end

  def show
    @question = Question.find(params[:question_id])

  end

  def update
  	@code = Code.update(set_params)
  end

  def destroy
  end

  private 
  	def set_code
  		@code = Code.find_by(params[:id])
  	end

  	def set_params
  		params.require(:code).permit(:solution)
  	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	 before_action :set_question, only:[:edit,:show,:update,:destroy]
	 before_action :authenticate_user!, except:[:index]
	 before_action :check_user , only:[:edit,:update,:destroy]

  def index
  	@programs = Question.all
  end

  def edit

  end

  def new
  	@program = Question.new
  end

  def create
  	@program = Question.create(set_params)
  	@program.user_id = current_user.id
  	@program.save
  	redirect_to action: 'show' , id: @program.id 

  end

  def show
  	@codes = Code.all
  end

  def update
  	
  	@program = @program.update(set_params)
    redirect_to action: 'show' , id: params[:id]  
  end

  def destroy
  		
  end

  private 
  	def set_question
  		@program = Question.find(params[:id])
 
  	end

  	def set_params
  		params.require(:question).permit(:program,:user_id)
  	end

  	def check_user
  		if @program.user_id != current_user.id
  				return redirect_to action: 'index'
        end
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/codes/edit.html.erb
<h1>Codes#edit</h1>
<p>Find me in app/views/codes/edit.html.erb</p>

app/views/codes/index.html.erb
<h1>Codes#index</h1>
<p>Find me in app/views/codes/index.html.erb</p>

app/views/codes/new.html.erb
<h1>Programing Qiestion</h1>
<%= @p.program %>
<h3>Type Your Solution </h3>
<%= simple_form_for @code ,:url => {:action => "create"} do |f| %>
<%= f.input :solution , :input_html => {:rows => 20} %>
<%= f.button :submit %>
<% end %>

app/views/codes/show.html.erb
<h1>Question</h1>
<%= @question.program %><br/>
<br/>
<h4> Solution to it </h4>
<%= @code.solution %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodeX</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <% if user_signed_in? %>
    <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
    <% else %>
    <%= link_to "Sign In", new_user_session_path %>
    <%= link_to 'sign_up', new_user_registration_path %>
    <% end %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= simple_form_for @program  do |f| %>

  <%= f.input :program , :input_html => {:rows => 20} %>
  <%= f.button :submit %>
<% end %>

app/views/questions/edit.html.erb
<%= render partial: "form"%>

app/views/questions/index.html.erb
<h1>Listing all the Questions </h1>
<% @programs.reverse.each do |p| %>
<h4> Programming Question </h4>
<div style="    width: 100%;
  min-height: 200px;
    background-color: lightcoral;
">
<%= p.program %>
</div>
<br/>
<p>Owner</p>
<%= p.user.email %><br/>
<%= link_to 'all solutions' , question_path(p) %> ||<%= link_to 'add solution' ,  new_question_code_path(p) %>

<% end %>

app/views/questions/new.html.erb
<%= simple_form_for @program  do |f| %>

  <%= f.input :program , :input_html => {:rows => 20} %>
  <%= f.button :submit %>
<% end %>

app/views/questions/show.html.erb
<h1>Question</h1>
<%= @program.program %><br/>
<%= link_to 'add solution' , new_question_code_path(@program) %>
<br/>
<% @codes.each do |c|  %>

	<% if c.question_id == @program.id %>
		<h1> Solution to it </h1>

		<%= c.solution %>
		<%= link_to 'Expand_solution' ,  question_code_path(@program,c) %>
	<% end %>
<% end %>
<p>Owner</p>
<%= @program.user.email %><br/>